# Generated by Django 4.2.5 on 2023-11-02 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_artist', models.CharField(max_length=100)),
                ('slogan', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='artist_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('phone_2', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='member_photo')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='artist.artist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.contact'),
        ),
    ]
